# Generated by Django 3.0.4 on 2020-03-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='price',
            field=models.FloatField(max_length=20),
        ),
    ]
