# Generated by Django 3.0.4 on 2020-03-17 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20200317_2254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
