# Generated by Django 3.0.4 on 2020-03-17 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_card_year_released'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
