# Generated by Django 3.0.4 on 2020-03-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0003_delete_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type_1', models.CharField(max_length=20)),
                ('type_2', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.FloatField()),
                ('year_released', models.DateTimeField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
