# Generated by Django 3.0.4 on 2020-03-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_auto_20200324_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='card_id',
            field=models.CharField(default=25, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='image_url',
            field=models.URLField(default='https://images.pokemontcg.io/xy1/42.png'),
            preserve_default=False,
        ),
    ]
